# Generated by Django 5.2.8 on 2025-11-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dark_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=99),
        ),
    ]
