# Generated by Django 5.2.8 on 2025-11-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dark_app', '0002_alter_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='Name',
        ),
    ]
